### ISSUE TITLE
Unable to `npm install` due to missing `babel-node` command

### ISSUE THREAD

**Issue by jared-stilwell** [typhonjs-node-escomplex/escomplex-core-commons#1]
When I `npm install`, I get an error:

```
> npm i

> escomplex-core-commons@2.0.0 prepublish /Users/jaredstilwell/Projects/escomplex-core-commons
> babel-node ./node_modules/typhonjs-npm-scripts-publish/scripts/prepublish.js

sh: babel-node: command not found

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/jaredstilwell/.nvm/versions/node/v4.4.5/bin/node" "/Users/jaredstilwell/.nvm/versions/node/v4.4.5/bin/npm" "i"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! escomplex-core-commons@2.0.0 prepublish: `babel-node ./node_modules/typhonjs-npm-scripts-publish/scripts/prepublish.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the escomplex-core-commons@2.0.0 prepublish script 'babel-node ./node_modules/typhonjs-npm-scripts-publish/scripts/prepublish.js'.
npm ERR! This is most likely a problem with the escomplex-core-commons package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./node_modules/typhonjs-npm-scripts-publish/scripts/prepublish.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs escomplex-core-commons
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls escomplex-core-commons
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jaredstilwell/Projects/escomplex-core-commons/npm-debug.log
```

**Comment by typhonrt** [comment]
I've designed the TyphonJS development support modules to work on Node 5+ with the flat package arrangement of NPM 3+. In particular it's [typhonjs-npm-build-test](https://www.npmjs.com/package/typhonjs-npm-build-test) which pulls in 5 sub modules and subsequently all of their dependencies including Babel. Everything works fine with Node 5+. IMHO the flat package change to NPM is a major feature that makes things much easier in bundling dependencies with just a single inclusion; IE: 
`"typhonjs-npm-build-test": "^0.1.0"`

It should be noted that this is for development and publishing concerns. When the modules are published they'll work on any version of Node. It looks like you are developing locally, so upgrading your Node version will do the trick. It's hard not to adopt the new Node features when v6 is already out and they are on an aggressive tick-tock cycle now with a major release every year.
